name: Remontée de Bug
description: Signalez un bug rencontré dans Haddock.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["haddock-project/1", "haddock-project/bug-tracking"]
assignees:
  - dev-haddock
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug. Nous apprécions votre contribution pour améliorer Haddock !
  - type: input
    id: contact
    attributes:
      label: Coordonnées
      description: Comment pouvons-nous vous contacter si nous avons besoin de plus d'informations ?
      placeholder: ex. email@exemple.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Décrivez le problème et ce que vous attendiez comme comportement.
      placeholder: Décrivez le bug observé ici.
      value: "Un bug est survenu !"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version de Haddock
      description: Quelle version de Haddock utilisez-vous ?
      options:
        - 1.0.0
        - 1.0.1 (Beta)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: environnement
    attributes:
      label: Environnement de travail
      description: Où avez-vous rencontré ce bug ?
      options:
        - Windows
        - macOS
        - Linux
        - Docker
      multiple: false
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Journaux d'erreurs
      description: Collez ici les journaux ou erreurs pertinents. Ce champ sera formaté automatiquement.
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code de Conduite
      description: En soumettant cette issue, vous acceptez de suivre notre [Code de Conduite](https://example.com).
      options:
        - label: J'accepte de respecter le Code de Conduite de ce projet.
          required: true
