name: Bug Report
description: Report a bug encountered in Haddock.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["haddock-project/1", "haddock-project/bug-tracking"]
assignees:
  - dev-haddock
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug. We appreciate your contribution to improving Haddock!
  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you if we need more information?
      placeholder: e.g. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue and what you expected to happen instead.
      placeholder: Describe the observed bug here.
      value: "A bug occurred!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Haddock Version
      description: Which version of Haddock are you using?
      options:
        - 1.0.0
        - 1.0.1 (Beta)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: environnement
    attributes:
      label: Environment
      description: Where did you encounter this bug?
      options:
        - Windows
        - macOS
        - Linux
        - Docker
      multiple: false
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant logs or error messages here. This field will be automatically formatted.
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project’s Code of Conduct.
          required: true
