name: Suggestion
description: Propose an idea or improvement for Haddock.
title: "[Suggestion]: "
labels: ["enhancement", "idea"]
projects: ["haddock-project/1", "haddock-project/enhancements"]
assignees:
  - dev-haddock
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sharing your ideas to make Haddock even better! We carefully review all suggestions.
  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you if we have questions about your idea?
      placeholder: e.g. email@example.com
    validations:
      required: false
  - type: textarea
    id: idea-description
    attributes:
      label: Description of Your Suggestion
      description: Explain your idea or improvement, and its potential impact on Haddock.
      placeholder: Describe your suggestion here.
    validations:
      required: true
  - type: checkboxes
    id: benefits
    attributes:
      label: Benefits
      description: What do you see as the benefits of this suggestion?
      options:
        - label: Improved user experience
        - label: Increased performance
        - label: Solves an existing issue
        - label: Other (please specify in the description)
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: What priority would you assign to this suggestion?
      options:
        - Low
        - Medium
        - High
      default: 1
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project’s Code of Conduct.
          required: true
