import { ServiceDto } from "@/services/backendApi/services";

export const mockedNodes: ServiceDto[] = [
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "backend",
    image: "node:16",
    ports: ["8080"],
    networks: ["app-network"],
    depends_on: ["database"],
    environment: ["NODE_ENV=development"],
    user: { gid: "1000", uid: "1000" },
    deployment: { memory: 512, cpus: 50 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "database",
    image: "postgres:13",
    ports: [],
    networks: ["app-network"],
    depends_on: [],
    environment: [
      "POSTGRES_USER=admin",
      "POSTGRES_PASSWORD=secretpassword",
      "POSTGRES_DB=mangadb",
    ],
    user: null,
    deployment: null,
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "frontend",
    image: "nginx:latest",
    ports: ["80"],
    networks: ["default"],
    depends_on: ["backend"],
    environment: [],
    user: null,
    deployment: { memory: 256, cpus: 20 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "cache",
    image: "redis:6",
    ports: [],
    networks: [],
    depends_on: [],
    environment: [],
    user: null,
    deployment: { memory: 128, cpus: 10 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "worker",
    image: "python:3.9",
    ports: [],
    networks: ["app-network"],
    depends_on: ["backend", "database"],
    environment: ["WORKER_ENV=production"],
    user: { gid: "2000", uid: "2000" },
    deployment: { memory: 256, cpus: 20 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "standalone",
    image: "alpine:latest",
    ports: ["8081"],
    networks: [],
    depends_on: [],
    environment: ["MODE=standalone"],
    user: { gid: "3000", uid: "3000" },
    deployment: null,
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "analytics",
    image: "python:3.8",
    ports: [],
    networks: ["default"],
    depends_on: ["worker"],
    environment: ["ANALYTICS_MODE=enabled"],
    user: null,
    deployment: { memory: 512, cpus: 40 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "load-balancer",
    image: "haproxy:2.4",
    ports: ["443", "80"],
    networks: ["app-network", "default"],
    depends_on: ["frontend", "backend"],
    environment: [],
    user: null,
    deployment: { memory: 1024, cpus: 100 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "scheduler",
    image: "python:3.10",
    ports: [],
    networks: ["app-network"],
    depends_on: ["worker"],
    environment: ["SCHEDULER_MODE=cron"],
    user: { gid: "4000", uid: "4000" },
    deployment: { memory: 128, cpus: 10 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "monitoring",
    image: "prometheus:latest",
    ports: ["9090"],
    networks: ["default"],
    depends_on: [],
    environment: [],
    user: null,
    deployment: { memory: 256, cpus: 30 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "logger",
    image: "fluentd:latest",
    ports: [],
    networks: [],
    depends_on: [],
    environment: ["LOG_LEVEL=info"],
    user: { gid: "5000", uid: "5000" },
    deployment: { memory: 64, cpus: 5 },
  },
  {
    icon: "https://i.imgur.com/ZMxf3Iy.png",
    name: "queue",
    image: "rabbitmq:3-management",
    ports: ["15672", "5672"],
    networks: ["app-network"],
    depends_on: ["worker"],
    environment: [
      "RABBITMQ_DEFAULT_USER=admin",
      "RABBITMQ_DEFAULT_PASS=secret",
    ],
    user: null,
    deployment: { memory: 512, cpus: 50 },
  },
];
