export default {
  prefixes: [
    'The',
    'Black',
    'The Red',
    'The Blue',
    'The Green',
    'The Yellow',
    'The White',
    'The Purple',
    'The Crimson',
    'The Golden',
    'The Silver',
    'The Iron',
    'The Steel',
    'The Wooden',
    'The Ghostly',
    'The Haunted',
    'The Cursed',
    'The Damned',
    'The Blessed',
    'The Holy',
    'The Unholy',
    'The Divine',
    'The Infernal',
    'The Inferno',
    'The Bloody',
    'The Drowned',
    'The Sinking',
    'The Floating',
    'The Drifting',
    'The Sailing',
    'The Flying',
    'The Soaring',
    'The Roaring',
    'The Whispering',
    'The Screaming',
    'The Laughing',
    'The Cackling',
    'The Singing',
    'The Dancing',
    'The Dark',
    'The Going',
    'The Coming',
    "Queen Anne's",
    "King George's",
    "Haddock's",
    'Sea',
    'The Jolly',
    'The Silent',
    'HMS',
    'The Dying',
    'Thriller',
    'The Thousand',
  ],
  suffixes: [
    'Jackdaw',
    'Pearl',
    'Revenge',
    'Merry',
    'Sparrow',
    'Rogue',
    'Vengeance',
    'Fury',
    'Storm',
    'Tempest',
    'Hurricane',
    'Tornado',
    'Whirlwind',
    'Cyclone',
    'Typhoon',
    'Monster',
    'Beast',
    'Dragon',
    'Kraken',
    'Giant',
    'Titan',
    'Ranger',
    'Diamond',
    'Haddock',
    'Swordfish',
    'Whale',
    'Shark',
    'Dolphin',
    'Orca',
    'Princess',
    'Siren',
    'Mermaid',
    'Serenity',
    'Harmony',
    'Peace',
    'Freedom',
    'Liberty',
    'Justice',
    'Honor',
    'Glory',
    'Victory',
    'Triumph',
    'Conquest',
    'Adventure',
    'Dream Catcher',
    'Escape',
    'Voyager',
    'Patriot',
    'Ariel',
    'Hawk',
    'Eagle',
    'Dutchman',
    'Roger',
    'Delight',
    'Dragon',
    'Mary',
    'Endeavour',
    'Gull',
    'Interceptor',
    'Moby Dick',
    'Bark',
    'Sunny',
    'Force',
    'Oro Jackson',
  ],
};
