services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_service
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'

  api:
    restart: unless-stopped
    expose:
      - 3000
    build:
      context: .
      dockerfile: Dockerfile.prod
    network_mode: "host"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres: